### ISSUE TITLE
Find a way to document and dispaly contributors

### ISSUE THREAD

**Issue by BenediktHensen** [ea-tel/detel-book#22]
Commits are made by one person but there might be more contributors in the background that should also be mentioned. We should look for a way how to document and track who participated in which chapter. This documentation should also track the kind of contribution that an author made.

**Comment by BenediktHensen** [comment]
On a technical level, future commits can be created this way: https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors

However, we should be aware that this exposes the mail address of the additional authors.

**Comment by BenediktHensen** [comment]
An alternative would be to let the authors enter their names and contributions directly in the chapter. We could adjust the chapter format so that there is a line at the top where the authors are listed together with their kind of contribution.

**Comment by fominykh** [comment]
> 

@BenediktHensen I think the safest option is to adjust the chapter format/template to add a small section at the top where the authors are listed together with a very short description of their contribution.

**Comment by fominykh** [comment]
> On a technical level, future commits can be created this way: https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors
> 
> However, we should be aware that this exposes the mail address of the additional authors.

This can be added as an option to the documentation,
