### ISSUE TITLE
differences on the to addresses the book is deployed

### ISSUE THREAD

**Issue by fominykh** [ea-tel/detel-book#47]
After this issue was resolved #14 , the book is deployed on two addresses:

https://ea-tel.eu/detel-book/toc/
https://ea-tel.github.io/detel-book/toc/

However, there is either a delay in the deployment to the https://ea-tel.eu/detel-book/toc/ or something is not deployed automatically...

I updated the TOC page, but it only updated here https://ea-tel.github.io/detel-book/toc/

@BenediktHensen, can you clarify?

**Comment by fominykh** [comment]
Looks like, there is just a slightly larger delay in the pages updating on https://ea-tel.eu/detel-book/ ...

**Comment by BenediktHensen** [comment]
Yes, https://ea-tel.github.io/detel-book is updated directly once the pipeline for deployment has completed.

https://ea-tel.eu/detel-book/ is only updated once per hour. I think it pulls the changes 35 minutes after the full hour, e.g. at 8:35, then again at 9:35 and so on.
This delay has technical reasons as we could not have a direct mirror of the GitHub pages site included in the ea-tel page. Instead, it pulls the built and deployed web page which is located on the gh-pages Git branch. This content is then copied into the ea-tel website.
